### ISSUE TITLE
Придумать изображение виселицы и функцию вывода ее на экран

### ISSUE THREAD

**Issue by sivan2203** [thepluxuryprince/HangmanGame#1]
Планируется вывод в консоль, используя символы +-_\/||. 
Должно быть несколько изображений виселицы для разного количества ошибок(всего 6 изображений).

**Comment by Alesha27** [comment]
задание №1(issue_1) выполнил. Функция создана void hangman(int n). Работает. От n зависит изображение функции. Функция покрыта тестами.
