### ISSUE TITLE
Написание main.c файла

### ISSUE THREAD

**Issue by thepluxuryprince** [thepluxuryprince/HangmanGame#12]
После того как будут готовы все функции надо написать main.c в котором будет выполнен цикл игры. Протестировать приложение. Последовательность игры: 
* Главное меню с выбором тем
* Открывается нужный txt файл с темами
* Рандомно выбирается слово
* На экране появляется изображение виселицы, скрытое загаданное слово, буквы которые игрок уже ввел
* Игрок пытается угадать слово, вводя буквы с клавиатуры 
* На каждой итерации игрового цикла проверка на победу и поражение
* После конца игры вывод соответствующего результата

**Comment by Alesha27** [comment]
Задание выполнено, добавил вывод виселицы на экран победы и поражения
