### ISSUE TITLE
Реализовать выбор тем(сценариев игры)

### ISSUE THREAD

**Issue by sivan2203** [thepluxuryprince/HangmanGame#3]
Функция выводит на экран меню для выбора тематики слов. 
После выбора темы игра идет по определенному сценарию.

**Comment by Alesha27** [comment]
Реализовал выбор тем в файле main.c. Добавил функцию вывода меню на экран mainMenuPrint. Текстовые файлы перенесены для работы в программе. Makefile дополнен ключами GBD отладчика.
