### ISSUE TITLE
Реализовать функцию проверки корректности вводимых символов 

### ISSUE THREAD

**Issue by sivan2203** [thepluxuryprince/HangmanGame#4]
Правильные вводимые символы - латинские буквы.

**Comment by thepluxuryprince** [comment]
Функция проверки ввода букв разработана isWordiuc. Функция кроме проверки, также выполняет трансформацию буквы к верхнему регистру(если введена буква в нижнем регистре). Кроме того добавил функцию, проверяющую корректность ввода темы isTheme. Обе функции покрыты тестами.
